version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    env_file:
      - .env.docker
    ports:
      - 3000:3000
    volumes:
      - ./logs/:/root/logs/
    restart: unless-stopped
    depends_on:
      - database
    networks:
      - app-tier

  database:
    image: postgres:14.5-alpine
    container_name: database
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: base-gin-golang
      PGDATA: /data/postgres
    volumes:
      - .docker/data/postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - app-tier
    restart: always

  redis:
    image: redis:7.0-alpine
    container_name: redis
    env_file:
      - .env.docker
    command: redis-server --save 60 1 --requirepass $REDIS_PASSWORD
    volumes:
      - .docker/data/redis:/data
    ports:
      - "6379:6379"
    networks:
      - app-tier
    restart: always

  elasticsearch:
    image: elasticsearch:8.3.2
    container_name: elasticsearch
    environment:
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    volumes:
      - ./infrastructure_config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
      - elasticsearch-data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - app-tier
    restart: always

  mongodb:
    image: mongo:6.0.5
    container_name: mongodb
    volumes:
      - .docker/data/mongodb:/data/db
    ports:
      - "27017:27017"
    networks:
      - app-tier
    restart: always

  logstash:
    image: logstash:8.3.2
    container_name: logstash
    volumes:
      - ./infrastructure_config/logstash.conf:/usr/share/logstash/pipeline/logstash.conf:ro
    depends_on:
      - elasticsearch
    networks:
      - app-tier
    restart: always

  filebeat:
    image: docker.elastic.co/beats/filebeat:8.3.2
    container_name: filebeat
    command: filebeat -e -strict.perms=false
    depends_on:
      - elasticsearch
    volumes:
      - ./infrastructure_config/filebeat.yml:/usr/share/filebeat/filebeat.yml
      - ./logs/:/logs/
    networks:
      - app-tier
    restart: always

  kibana:
    image: kibana:8.3.2
    container_name: kibana
    depends_on:
      - elasticsearch
    ports:
      - 5601:5601
    networks:
      - app-tier
    restart: always

networks:
  app-tier:
    driver: bridge
    name: app-tier

volumes:
  elasticsearch-data:
    driver: local
