// Code generated by MockGen. DO NOT EDIT.
// Source: base-gin-golang/pkg/errors (interfaces: Service)

// Package errors is a generated GoMock package.
package errors

import (
	custom "base-gin-golang/pkg/errors/custom"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// ParseInternalServer mocks base method.
func (m *MockService) ParseInternalServer(arg0 error) custom.CustomError {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ParseInternalServer", arg0)
	ret0, _ := ret[0].(custom.CustomError)
	return ret0
}

// ParseInternalServer indicates an expected call of ParseInternalServer.
func (mr *MockServiceMockRecorder) ParseInternalServer(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ParseInternalServer", reflect.TypeOf((*MockService)(nil).ParseInternalServer), arg0)
}
