// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"base-gin-golang/config"
	"base-gin-golang/infra/postgresql"
	"base-gin-golang/infra/postgresql/repository"
	"base-gin-golang/pkg/data"
	"base-gin-golang/pkg/errors"
	"base-gin-golang/pkg/jwt"
	"base-gin-golang/pkg/password"
	string2 "base-gin-golang/pkg/string"
	"base-gin-golang/usecase/auth"
	"base-gin-golang/usecase/product"
)

// Injectors from wire.go:

func InitApp(config2 *config.Environment, database *postgresql.Database) (App, error) {
	service := data.NewDataService()
	stringService := string2.NewStringService()
	jwtService := jwt.NewJwtService(config2)
	passwordService := password.NewPasswordService()
	errorsService := errors.NewErrorService(config2)
	productRepository := repository.NewProductRepository(database, service)
	userRepository := repository.NewUserRepository(database, service)
	useCase := product.NewProductUseCase(productRepository, service, database)
	authUseCase := auth.NewAuthUseCase(config2, jwtService, passwordService, userRepository)
	app := newApp(service, stringService, jwtService, passwordService, errorsService, productRepository, userRepository, useCase, authUseCase)
	return app, nil
}
